name: ISO

on:
  schedule:
    - cron: "00 07 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Setup Bluebuild
        run: docker run --pull always --rm ghcr.io/blue-build/cli:latest-installer | bash

      - name: Build ISO
        run: bluebuild generate-iso --iso-name simpl-os.iso image ghcr.io/moe-os/simpl-os:latest

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@v1
        with:
          endpoint: ${{ secrets.S3_URL}}
          aws_key_id: ${{ secrets.S3_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          source_dir: "."
